### PR TITLE
Fixing issue #17 for Python 2

### PR DESCRIPTION
**Pull request by dantaeyoung**
This PR resolves Issue #17 for Python 2 also -- tested on Python 2.7.11 and 3.5.2.

### CODE REVIEW

**Comment by jimboca** [comment]
@provolot if you or @Teagan42 can fix the conflict with my changes, I will test this in my environment and see if it resolves my issues as well.

**Comment by jimboca** [comment]
Since this merge is for #17 and includes all of @Teagan42 changes, which I have to defer to @rmkraus to approve, I will make just the specific change for #17 and just merge that.

**Comment by jimboca** [comment]
Still have conflicts, can not be merged.

**Comment by Teagan42** [comment]
Those are new - fixing

**Comment by Teagan42** [comment]
I am so confused - I just did a pull from master to my fork - no difference

**Comment by jimboca** [comment]
That comment was on @provolot fork, not yours?

**Comment by Teagan42** [comment]
I realized that shortly after posting - my bad, slightly stoned.

**Pull request closed without merging**
