### PR TITLE
Guard against downstream errors interrupting the socket connection

### PR DESCRIPTION
**Pull request by bdraco**
Same as #248, but for 3.x

Fixes https://github.com/home-assistant/core/issues/66003

### CODE REVIEW

**Comment by shbatm** [comment]
I already included this in 3.0.3.

**Comment by shbatm** [comment]
Well shit... I thought I did...

**Review by shbatm — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @shbatm  👍

**Comment by bdraco** [comment]
@shbatm Looks like something went wrong with the publish as 3.0.4 is missing from PyPI

**Pull request merged**
