### PR TITLE
Expose more params

### PR DESCRIPTION
**Pull request by OverloadUT**
**Note: this PR is branched off of PR #35, and should be merged after**

This simply adds a few more attributes to the Node object that come from the ISY's payload that I needed when improving the ISY994 support in Home Assistant:

* `nid` is the node id. It was only available in a protected property before. This was added mainly because of the parent_nid use-case below.
* `node_def_id` is the NodeDefId introduced in the 5.x builds of the ISY firmware. They make determining the broad type of device such as dimmer, relay, sensor very convenient.
* `parent_nid` is the parent node - this only applies when a single device uses multiple nodes (like sensors, keypads, and multi-button remotes). In addition to exposing the `parent_nid` string, there is also a `parent_node` property that will return the parent node itself.
* `type` is the type parameter from ISY, which represents the exact physical hardware that a node comes from. This is necessary to determine if a node is a motion sensor, leak sensor, etc.

### CODE REVIEW

**Comment by rmkraus** [comment]
This all appears safe with the 4.x.x firmware.

There are a couple blank except statements in this as well. Would it be possible to make them more specific?

A comment about using node_def_id in Home Assistant. You should make Home Assistant's dependance on this value optional. That is to say, you can default to using node_def_id when sorting nodes, but fall back to the existing logic if the node_def_id is not available. Since 4.x.x firmware is the officially supported firmware, I don't want to drop support for it.

**Comment by rmkraus** [comment]
Other than those comments, I have no issue with this PR.

**Comment by OverloadUT** [comment]
All wildcard except clauses have been fixed!

Regarding `node_def_id`: Yes, I am ensuring the additions to Home Assistant don't break if the 5.x.x firmware is missing. Right now the new functionality will only benefit 5.x.x users, but I am thinking I should change that and add some `type` parsing as a fallback, since I ended up having to parse the type attribute anyway.

**Comment by rmkraus** [comment]
👍

**Pull request merged**
