### PR TITLE
Fix #39

### LINKED ISSUE #39: Exceptions when loading nodes (Firmware 5.0.11c)
Some ISY Node Server Nodes (e.g. n002_huegrp0) do not have a parent status and throw an error when processing groups during initialization.  I do not have the exact error traceback, but it amounted to something along the lines of "cannot compare type NoneType to type Int with >".

Apparent Fix:
Update `group.py` [line 83](https://github.com/automicus/PyISY/blob/master/PyISY/Nodes/group.py#L83) to the following:
```python
            if self.parent[m].status == None:
                continue
            elif self.parent[m].status > 0:
```

### PR DESCRIPTION
**Pull request by exking**

### CODE REVIEW

**Comment by ludeeus** [comment]
Just tested this, and it do works :+1:
Thanks @exking 🎉

**Comment by shbatm** [comment]
Confirmed this works.

**Comment by shbatm** [comment]
Sorry to bother. any updates on when this PR may be incorporated?

HomeAssistant has started a nasty habit of reverting any PyPi package changes made between reloads of a Docker container--long way of stating right now I have to fix this file every time I restart my server.

**Comment by rmkraus** [comment]
So I am actually in the middle of a move and don't really have a full setup right now. It does look like two different people have verified this fix, though. (and it is only a few lines)

I'll merge and push an update tonight. I won't be able test with Home Assistant, though. Someone else will have to make the PR for HASS. (That should be easy, though).

**Comment by shbatm** [comment]
OK thanks for the update. I'll be happy to send the PR to HASS once PyPi is updated to the new version.

**Pull request merged**
