### PR TITLE
Prevent callback exception from disconnecting websocket

### PR DESCRIPTION
**Pull request by bdraco**
Fixes https://github.com/home-assistant/core/issues/66003

### CODE REVIEW

**Comment by shbatm** [comment]
Is this related to this: https://forum.universal-devices.com/topic/34978-ha-error-adding-isy994/ by any chance?

On my phone and haven't dug in

**Comment by shbatm** [comment]
@bdraco I'm curious how you got to wrapping this function from the traces on https://github.com/home-assistant/core/issues/66003. I'm not following something... this function is called just to trigger the state update callback in HA and the associated groups' state--it's called well down the line from processing done on a message from the websocket.

**Comment by bdraco** [comment]
I wrapped it at the point where PyISY is no longer in control of the code its executing.  Since it can't reasonably know what that code is going to do, it seemed like the best place to put the broad exception catch.

**Comment by shbatm** [comment]
OK. Now I understand; you're guarding against downstream, not trying to protect from a bad message from the socket.

**Comment by bdraco** [comment]
> OK. Now I understand; you're guarding against downstream, not trying to protect from a bad message from the socket.

Exactly

**Pull request merged**
